from fastapi import APIRouter, Depends, Body, HTTPException, Request
from sqlalchemy.orm import Session

from app.api.rbac import require_roles
from app.api.security import get_current_user
from app.db.session import get_db
from app.models.order import Order, OrderStatus
from app.models.order_item import OrderItem
from app.models.user import User
from app.schemas.orders import OrderCreate, OrderOut
from app.services.orders_service import (
    get_order,
    reserve_stock_for_order,
    restock_for_order,
    transition,
)

router = APIRouter(
    prefix="/orders",
    tags=["Orders"],
    dependencies=[Depends(require_roles("admin", "operator", "service"))],
)


def _request_id(request: Request) -> str | None:
    # Prefer request_id generated by middleware; fallback to client-provided header
    rid = getattr(request.state, "request_id", None)
    return rid or request.headers.get("X-Request-ID")


@router.post("", response_model=OrderOut, summary="Create order")
def create_order(
    request: Request,
    payload: OrderCreate = Body(
        ...,
        example={
            "customer_id": 1,
            "reference": "NL-ORDER-001",
            "items": [
                {"product_id": 1, "qty": 2},
                {"product_id": 2, "qty": 1},
            ],
        },
    ),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = Order(customer_id=payload.customer_id, reference=payload.reference, status=OrderStatus.NEW)
    db.add(order)
    db.flush()

    for it in payload.items:
        db.add(OrderItem(order_id=order.id, product_id=it.product_id, qty=it.qty))

    db.commit()
    db.refresh(order)
    return order


@router.get("/{order_id}", response_model=OrderOut, summary="Get order")
def read_order(
    order_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return get_order(db, order_id)


@router.post("/{order_id}/reserve", response_model=OrderOut, summary="Reserve stock")
def reserve(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # Idempotency (only for the target state)
    if order.status == OrderStatus.RESERVED:
        return order

    # Policy: retry explicitly via /retry-reserve
    if order.status == OrderStatus.FAILED_RESERVATION:
        raise HTTPException(status_code=409, detail="Order previously failed reservation")

    rid = _request_id(request)

    try:
        reserve_stock_for_order(db, order_id)
        transition(db, order, OrderStatus.RESERVED, actor=current_user, request_id=rid)
        db.commit()
        db.refresh(order)
        return order

    except HTTPException as e:
        db.rollback()

        # For insufficient stock (409), mark FAILED_RESERVATION + audit it
        if e.status_code == 409:
            order = get_order(db, order_id)
            transition(db, order, OrderStatus.FAILED_RESERVATION, actor=current_user, request_id=rid)
            db.commit()
            db.refresh(order)

        raise

    except Exception:
        db.rollback()
        raise


@router.post("/{order_id}/start-pick", response_model=OrderOut, summary="Start picking")
def start_pick(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # idempotent only if already in target state
    if order.status == OrderStatus.PICKING:
        return order

    # strict: can only start picking from RESERVED
    if order.status != OrderStatus.RESERVED:
        raise HTTPException(
            status_code=409,
            detail=f"Cannot start picking from {order.status}. Expected {OrderStatus.RESERVED}.",
        )

    transition(db, order, OrderStatus.PICKING, actor=current_user, request_id=_request_id(request))
    db.commit()
    db.refresh(order)
    return order


@router.post("/{order_id}/confirm-pick", response_model=OrderOut, summary="Confirm picked")
def confirm_pick(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # idempotent only if already in target state
    if order.status == OrderStatus.PICKED:
        return order

    # strict: can only confirm pick from PICKING
    if order.status != OrderStatus.PICKING:
        raise HTTPException(
            status_code=409,
            detail=f"Cannot confirm pick from {order.status}. Expected {OrderStatus.PICKING}.",
        )

    transition(db, order, OrderStatus.PICKED, actor=current_user, request_id=_request_id(request))
    db.commit()
    db.refresh(order)
    return order


@router.post("/{order_id}/ship", response_model=OrderOut, summary="Ship order")
def ship(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # idempotent only if already in target state
    if order.status == OrderStatus.SHIPPED:
        return order

    # strict: can only ship from PICKED
    if order.status != OrderStatus.PICKED:
        raise HTTPException(
            status_code=409,
            detail=f"Cannot ship from {order.status}. Expected {OrderStatus.PICKED}.",
        )

    transition(db, order, OrderStatus.SHIPPED, actor=current_user, request_id=_request_id(request))
    db.commit()
    db.refresh(order)
    return order


@router.post("/{order_id}/cancel", response_model=OrderOut, summary="Cancel order")
def cancel(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # idempotent only if already in target state
    if order.status == OrderStatus.CANCELLED:
        return order

    # strict rule: cannot cancel shipped
    if order.status == OrderStatus.SHIPPED:
        raise HTTPException(status_code=409, detail="Cannot cancel a shipped order")

    rid = _request_id(request)

    try:
        # Restock only if stock was decremented earlier
        if order.status in (OrderStatus.RESERVED, OrderStatus.PICKING, OrderStatus.PICKED):
            restock_for_order(db, order_id)

        transition(db, order, OrderStatus.CANCELLED, actor=current_user, request_id=rid)
        db.commit()
        db.refresh(order)
        return order

    except Exception:
        db.rollback()
        raise


@router.post("/{order_id}/retry-reserve", response_model=OrderOut, summary="Retry reserve stock")
def retry_reserve(
    order_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    order = get_order(db, order_id)

    # Idempotency (only for target state)
    if order.status == OrderStatus.RESERVED:
        return order

    # strict: retry only from FAILED_RESERVATION
    if order.status != OrderStatus.FAILED_RESERVATION:
        raise HTTPException(
            status_code=409,
            detail=f"Retry reserve allowed only for FAILED_RESERVATION. Current: {order.status}",
        )

    rid = _request_id(request)

    try:
        reserve_stock_for_order(db, order_id)
        transition(db, order, OrderStatus.RESERVED, actor=current_user, request_id=rid)
        db.commit()
        db.refresh(order)
        return order

    except HTTPException as e:
        db.rollback()

        # If still no stock, keep FAILED_RESERVATION but audit the re-failure
        if e.status_code == 409:
            order = get_order(db, order_id)
            transition(db, order, OrderStatus.FAILED_RESERVATION, actor=current_user, request_id=rid)
            db.commit()
            db.refresh(order)

        raise

    except Exception:
        db.rollback()
        raise